@startuml
skinparam class {
	BackgroundColor PaleGreen
	ArrowColor SeaGreen
	BorderColor SpringGreen
}
skinparam stereotypeCBackgroundColor YellowGreen

abstract class BaseJdbcLogger
class StatementLogger
class ConnectionLogger
class ResultSetLogger
class PreparedStatementLogger
interface InvocationHandler


BaseJdbcLogger <|-- StatementLogger
BaseJdbcLogger <|-- ConnectionLogger
BaseJdbcLogger <|-- ResultSetLogger
BaseJdbcLogger <|-- PreparedStatementLogger

StatementLogger ..|> InvocationHandler
ConnectionLogger ..|> InvocationHandler
ResultSetLogger ..|> InvocationHandler
PreparedStatementLogger ..|> InvocationHandler

@enduml